# Generated by Django 4.1 on 2023-01-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='contraseña',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registros',
            name='correo',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
